name = "MatrixEnsembles"
uuid = "c7015dd7-3fb7-4a4c-827e-526313618491"
authors = ["≈Åukasz Pawela <lukasz.pawela@gmail.com>"]
version = "0.1.3"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DocStringExtensions = "0.8.3"
Requires = "1.1"
StatsBase = "0.33.2"
julia = "1.4, 1.5"
CUDA = "2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
